
@url_dev=http://localhost:3055/v1/api


### signUp
POST {{url_dev}}/shop/signUp
Content-Type: application/json
x-api-key: 3abb4a966cd6d799315d767ad3b79be46cebbe5fc3d978b69cc0c5f906eaf5d03dee6a8252a225d60d94f20d0d2c04bfcb5e2df9da33410038157c5b9c85c19b

{
    "name": "SHOP TIPS",
    "email": "SHOPDEV_logout@gmail.com",
    "password": "abc123"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 3abb4a966cd6d799315d767ad3b79be46cebbe5fc3d978b69cc0c5f906eaf5d03dee6a8252a225d60d94f20d0d2c04bfcb5e2df9da33410038157c5b9c85c19b

{
    "email": "SHOPDEV@gmail6.com",
    "password": "abc123"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 3abb4a966cd6d799315d767ad3b79be46cebbe5fc3d978b69cc0c5f906eaf5d03dee6a8252a225d60d94f20d0d2c04bfcb5e2df9da33410038157c5b9c85c19b
x-client-id: 651d1b86ec9835d0776f4138
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMWI4NmVjOTgzNWQwNzc2ZjQxMzgiLCJlbWFpbCI6IlNIT1BERVZfbG9nb3V0QGdtYWlsLmNvbSIsImlhdCI6MTY5NjQwOTQxMSwiZXhwIjoxNjk2NTgyMjExfQ.d-4G-0fS_bV0AFXSSyh1Vl9q_tLs-xLkjyz9aefDLFJMScMr9uQi-H9IUiBrYbH-BeL8oS2VG28nolsXE77Gm9nMcdCGgUD0icncIo3Zmj8FJMpJqMR4mVUgR-P3ATRUmBgxqThMHUj-km9_0XQHRRCnLtTjrc6Vykc4oI6oWMr1Rg2vPEj4jpVgpBilTjzYXFttSvJFkiyKtiGmxFLWgHgMLJ39gL0lgibyjExDcRgQdmdIgXBdSYuFoXCDk_zx9H1yHuG3Pw1oJFFpnktOFGE7WnPaA3gVb3FbOzWOQAX15hi8FrKIWLu2rgfuK4BI8qDEIf0_xokPW3jzEumUD9KlIQbcdxGzh8Kc_XE9JYSUyWIgjPynM7HCNP8dlBOPPEZ-441EL73XPDQSly9Vz1qS7ZSlQ7ZF-yCH7rRD-6WQEpeYOq1tXlgDr0Hodrzls1heSWrAuM7KoSHJPL71joiNO1Nkkun7U-gAMcu5KYOAfkfq7DYg-V3WpBY378RF91Nsg1_-0oBhxuN6H6ZXjr3yGhNV5MWAziXQBdN4Tc_FmtSyT99q4y1Ub031UqTJI9KINH2EIue7aRXpyB--JHtNap8E7r_2EiSHa6RRnlnvjEFUKtu20CtR-BkaqhdEy5skkGMtZ6OoO-Fk0HG809OgMNjXJblJ8kpjTS3G0YI

### handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: 3abb4a966cd6d799315d767ad3b79be46cebbe5fc3d978b69cc0c5f906eaf5d03dee6a8252a225d60d94f20d0d2c04bfcb5e2df9da33410038157c5b9c85c19b
x-client-id: 651d1b86ec9835d0776f4138
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMWI4NmVjOTgzNWQwNzc2ZjQxMzgiLCJlbWFpbCI6IlNIT1BERVZfbG9nb3V0QGdtYWlsLmNvbSIsImlhdCI6MTY5NjQ5OTAxMCwiZXhwIjoxNjk2NjcxODEwfQ.cH1KTOnRuFyMx9QMYXV_mOS9UJFXOzIpSxoFYbJps5wrJzxKu1osBoLds3dVgjHx8lUbD-09roAJfrahxC7ld_sECqdroFRwNC97Gv633ll35Pa5Tgn21d7I1GXi5JWgdt2yafm0p9SlZoyJYB0Z3FZB2LRDSbhWR-AaOYaCsSjqn0C5qxtcCXF0NHrJJU15tORo0NPcoqq0IQXsmMB5_VDeg7ApPLxFdCqUlXVyeM8ijNLhxVmNFMYGWG1HyU7HgG5zhSqfdcErBJrybkyMYzlMBuTFAVk5Qtni9ckFUkG-p5bIQ3eahaoqflGOqAwDtWPwkZ0VQ5Jx030SMasrdpQiPyrLiPH1akF06_Q6-lGZYHDrYLhwY8MOwQOtlE9tPXIok4Ta8p9FqIO8MW7vUs9D6EqUT15iKkAS1UMRNZrG4xmw5VzFP1pc9c9ndm3WA3abSdVjJXCvoc-DXyJ0vinu1EUIVRqf-0eBvk422xCUmwDNdnow4gYqJEM53rMfgMsj7uEklohlT02ihBw6Jp5kNirYGVaXJQex5ZzG6Qn47jg019LQcBrqZm2Ege0X8q6HzORVZYGvx3wERqff4eXoblwcZRWoZjYGkrzN5oiIIiH17s40BtKMcX9fSkW-BekwkjZBQQFjDjQL2Mduuf17AIRrxRaNwU18CkXY4j4

{
"refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkMWI4NmVjOTgzNWQwNzc2ZjQxMzgiLCJlbWFpbCI6IlNIT1BERVZfbG9nb3V0QGdtYWlsLmNvbSIsImlhdCI6MTY5NjQ5OTAxMCwiZXhwIjoxNjk3MTAzODEwfQ.Q_xnGInsshzBCt5RSzs1C_VlHzIyk5YXJNyoSDG14Yctg_LTVLDnX1eh6NQR2T8nlpmFd-W2Z1H8EHVbaGx9xv8VCvocr-n33MDOMhPqaVakjiwPKZ8o_uzIcX9sTxJp6D8pRZRRsI5z4HKCi1Nn8EChVVqgbAqJJSD4UaXkgw736oCjMr0g0XHeaE2zuB_Ner3CZD9eoFNbtz8b0k6t4tum_8d-75bFAPMhhYlvMv9jfrHFvjVV4-23ibvTnAsNLJbBzQv3pUYHT0JgG2Fl3oRqKDEKbGiEjRRVYdx0fVGWFsvKiMcc8EcrGu8bq00RqWSqOMfBX5ctVVCL6iylN1wWt2oxhEpC_Lvq_q22nDMzBXOwmE-bkd-xgr4gk0hT8UnBL_Lf7VPaoFgn3DbsbEoRLrv-x3uNtwIQhpEDnwXy-jORw9IDGyRsEJ4dyyMpAH6E8MfnwExRzGW8_lKfMUuQgoB4BAOIGETBUK1HcMiFUjOCExSUhFnYT0-9L8KxpyXCNm_8iMJY68S6oUNolPm6bQa33fXL_Sqvmx9PNooqTgK0lB3MZY3Oj_axi6fLNs5uMdDkXPD0d-GyHShn3vckO63NZ9lko1gTPWRmQEniN4e2sQ0sBMX9btZXLoBD0LyqzkfGJZj9Pe8-jci-XAe8AOOrpuWsTf5uiSIY5aE"
}
